from aiogram.fsm.state import State, StatesGroup

class DetectiveStates(StatesGroup):
    waiting_thought = State()
    waiting_anxiety_before = State()
    waiting_distortion = State()
    waiting_threat_type = State()
    waiting_unknown = State()
    waiting_evidence_for = State()
    waiting_evidence_against = State()
    waiting_probability = State()
    waiting_impact = State()
    waiting_verdict = State()
    waiting_reframed = State()
    waiting_belief = State()
    waiting_other_emotion = State()
    waiting_control = State()
    waiting_body_location = State()
    waiting_breathing = State()
    waiting_micro_action = State()
    waiting_custom_action = State()
    waiting_no_compulsion = State()
    waiting_anxiety_after = State()
    waiting_bridge_action = State()